service: renalizapp-2023

custom:
  myStage: ${opt:stage, self:provider.stage}
  myEnvironment:
    project:
      prod: "renalizapp-2023"
      dev: "renalizapp-dev-2023-396503"

package:
  patterns:
    - '!node_modules/**'
  excludeDevDependencies: true

provider:
  name: google
  runtime: nodejs16
  stage: ${opt:stage, 'dev'}
  project: ${self:custom.myEnvironment.project.${self:custom.myStage}}
  credentials: ${env:CREDENTIALS_PATH}
  labels:
    application: renalizapp-api

plugins:
  - serverless-google-cloudfunctions

functions:
  getAllBlogs:
    handler: getAllBlogs
    events:
      - http: get
    labels:
      team: gcf-team
  getTestById:
    handler: getTestById
    events:
      - http: id
    labels:
      team: gcf-team
  postTestResults:
    handler: postTestResults
    events:
      - http: testresults
    labels:
      team: gcf-team

