# serverless.yml
service: renalizapp-2023

custom:
  myStage: ${opt:stage, self:provider.stage}
  myEnvironment:
    project:
      prod: "renalizapp-2023"
      dev: "renalizapp-dev-2023-396503"

package:
  patterns:
   - '!node_modules/**'
  excludeDevDependencies: true
provider:
  stage: ${opt:stage, 'dev'}
  name: google
  project: ${self:custom.myEnvironment.project.${self:custom.myStage}}
  credentials: ${env:CREDENTIALS_PATH}
  labels:
    application: renalizapp-api
plugins:
  - serverless-google-cloudfunctions
functions:
  createUser:
    handler: createUser
    events:
      - http: 'POST /users'
    labels:
      team: backend-team
